// Reference content for the /categories page. `kind` already determines P&L treatment, so the
// page derives the P&L badge from KIND_INFO; DESCRIPTIONS adds plain-English "when to use" notes
// for the non-obvious categories (the everyday expense/income ones are self-explanatory).

export type CategoryKind =
  | "income"
  | "expense"
  | "non_deductible"
  | "transfer"
  | "funding"
  | "capital"
  | "liability"
  | "unclassified";

export const KIND_INFO: Record<CategoryKind, { label: string; pnl: "income" | "expense" | "no" | "flag"; blurb: string }> = {
  income: { label: "Income", pnl: "income", blurb: "Money earned — counts as income on the P&L." },
  expense: { label: "Expense", pnl: "expense", blurb: "Money spent on the business/household — a deductible expense on the P&L." },
  non_deductible: { label: "Non-deductible", pnl: "flag", blurb: "Real money spent, but NOT tax-deductible — shown separately and kept out of deductible expense totals." },
  transfer: { label: "Transfer", pnl: "no", blurb: "Money moving between your own accounts/entities. Never an expense or income — excluded from the P&L." },
  funding: { label: "Funding / Equity", pnl: "no", blurb: "Owner capital or inter-entity funding (equity in/out). A balance-sheet movement, not P&L." },
  capital: { label: "Capital / Asset", pnl: "no", blurb: "A capitalized purchase or improvement — an asset that depreciates over time, not an immediate expense." },
  liability: { label: "Liability", pnl: "no", blurb: "Loan principal or a payable — pays down debt on the balance sheet. (Only the interest portion is an expense.)" },
  unclassified: { label: "Unclassified", pnl: "no", blurb: "Not yet categorized — counts nowhere until you classify it." },
};

export const KIND_ORDER: CategoryKind[] = [
  "income", "expense", "non_deductible", "transfer", "funding", "capital", "liability", "unclassified",
];

// full_path -> description. Shared across entities where the meaning is identical.
export const DESCRIPTIONS: Record<string, string> = {
  "Transfer / Zelle (personal, not P&L)":
    "Moving YOUR OWN money — between your accounts (e.g. to savings) or funding a business you own. NOT for paying someone for a service (that's an expense like Contract Labor). Excluded from P&L.",
  "Credit card payment":
    "Paying down a credit-card balance. A cash transfer to the card — the original purchases on the card are the expenses, not the payment.",
  "Credit card rewards / cash back":
    "Card reward / cash-back credits. Treated as a rebate, not income. Excluded from P&L.",
  "Refund / credit": "A refund or merchant credit reversing a prior charge. Nets against spend; not income.",
  "Owner Contribution": "Owner putting personal money INTO this entity (capital in). Equity, not income — excluded from P&L. Pairs with a 'Transfer' out on the funding account.",
  "Owner Distribution": "Money taken OUT of the entity to the owner (a draw). Equity, not an expense — excluded from P&L.",
  "Owners Equity": "Owner-equity movements (contributions / draws). Balance sheet, not P&L.",
  "Owners Equity:Owner Distribution": "Money taken OUT of the entity to the owner (a draw). Equity, not an expense — excluded from P&L.",
  "Intercompany — pending": "A transfer between your entities awaiting pairing with its other half. A holding bucket — excluded from P&L until reconciled.",
  "Sales Tax Payable": "Sales tax you collected and owe to the state — a liability you remit, not income or expense.",
  "Security deposit movement": "Tenant security deposit held or returned — a liability you hold, not rental income.",
  "Mixed / pending allocation": "Holding bucket for charges that mix purposes or need a manual look — allocate before you finalize.",
  "Ask My Accountant": "A parking spot for anything you're unsure about — flag it for your accountant and revisit before close.",
  "Property purchase": "Buying the property itself — a capitalized asset (depreciated), not an expense.",
  "Leasehold Improvements": "Build-out / improvements to a leased space — a capitalized asset (depreciated), not an immediate expense.",
  "Leasehold improvements": "Build-out / improvements to a leased space — a capitalized asset (depreciated), not an immediate expense.",
  "Tenant improvement allowance": "Landlord allowance toward your build-out — offsets the improvement cost; capital, not income.",
  "Tax Penalty": "Tax penalties / fines — real money spent but NOT tax-deductible.",
  "Mortgage principal payment": "The PRINCIPAL portion of a mortgage payment — pays down the loan (balance sheet). Only the INTEREST portion is a deductible expense.",
  "Mortgage principal — primary home": "The PRINCIPAL portion of your home mortgage — pays down the loan. Not deductible; the interest portion is.",
  "Ford Motor Credit - F150:Principal": "The PRINCIPAL portion of the F-150 loan payment — pays down the loan, not an expense. The interest portion is the expense.",
  "Tournament Prep": "Athlete preparation costs for competition (recovery, medical, camps) — a business expense.",
  "Tournament Fees": "Competition entry / registration fees — a business expense.",
  "Franchise Fees": "Gracie Barra franchise / royalty fees — a business expense.",
  "Cost of Goods Sold:School Wear": "Apparel & gear inventory you resell at the academy — cost of goods sold.",
  "Cost of Goods Sold": "Inventory / goods you resell — cost of goods sold.",
  "→ Austin ACAA (136 Anita)": "Intercompany pointer: this charge actually belongs to Austin ACAA — routed there, not counted on this entity's P&L.",
  "→ GBSL business expense": "Intercompany pointer: this charge is really a GBSL business expense — routed to GBSL, not counted here.",
  "→ Keller business expense": "Intercompany pointer: this charge is really a Keller business expense — routed to Keller, not counted here.",
  "→ Pflugerville rental": "Intercompany pointer: this charge belongs to the Pflugerville rental — routed there, not counted here.",
  "→ Personal (mis-posted)": "Intercompany pointer: a personal charge that hit a business card — routed back to Personal, not a business expense.",

  // — Business expense chart (GBSL / Keller — many paths are shared) —
  "Advertising & Marketing": "Ads, promos, social/website spend to bring in members. Deductible business expense (Sch C, Line 8).",
  "Auto Expense": "Business-vehicle costs (fuel, repairs, registration). Use the Fuel / Parking sub-accounts where present; the CPA picks actual-expense vs mileage.",
  "Auto Expense:Fuel": "Gas / charging for a business vehicle.",
  "Auto Expense:Parking & Tolls": "Parking and tolls while on business.",
  "Bank Fees": "Bank-account fees & service charges. NOT card-processing (that's Merchant Fees).",
  "Bank fees": "Bank-account fees & service charges.",
  "Bank fees & Service charges": "Bank-account fees & service charges.",
  "Business Licenses and Permits": "Business licenses, permits, registrations. Deductible (Sch C, Line 23).",
  "Continuing Education": "Training, courses, certifications that maintain or improve business skills.",
  "Contract Labor": "Payments to non-employee 1099 contractors for services. NOT payroll — watch the 1099 threshold.",
  "Contractors *Needs review for 1099s*": "Non-employee contractor payments — flagged to confirm a 1099 is filed.",
  "Charitable Contributions": "Business charitable giving. For a pass-through this often flows to the owner's Sch A — the CPA places it.",
  "Dues & Subscriptions": "Professional dues, memberships, recurring subscriptions used for the business (distinct from one-off Software).",
  "Equipment": "Equipment purchases — usually capitalized & depreciated by the CPA if over the threshold, not an immediate expense.",
  "Events/Supplies": "Costs + supplies for gym events / tournaments.",
  "Gift": "Business gifts — deductible up to $25 per recipient per year.",
  "Insurance": "Business insurance premiums (liability, property). NOT health insurance — that's personal.",
  "Insurance Expense": "Business insurance premiums.",
  "Interest Expense": "Interest on business loans/cards — deductible. The principal portion is a liability, not an expense.",
  "Janitorial Supplies": "Cleaning supplies for the space.",
  "Job Supplies": "Consumables used to deliver the service (mats, tape, training gear).",
  "Job Supplies Expense": "Consumables used to deliver the service.",
  "Legal & Professional Fees": "Lawyers, accountants, consultants. Use the Accounting / Legal / Professional sub-accounts where present.",
  "Legal & Professional Fees:Accounting Fees": "Bookkeeping / accounting / tax-prep fees.",
  "Legal & Professional Fees:Legal Fees": "Attorney fees.",
  "Legal & Professional Fees:Professional Fees": "Other professional / consulting fees.",
  "Legal Fees": "Attorney fees.",
  "Legal & professional fees": "Lawyers, accountants, advisors (personal — deductibility is limited; the CPA decides).",
  "Licenses and Permits": "Business licenses, permits, registrations.",
  "Meals (50%)": "Business meals — 50% deductible (the default for most client / staff meals).",
  "Meals (100%)": "Fully-deductible meals (e.g. staff events, or when the current 100% rule applies) — use only when it does.",
  "Meals & Entertainment": "Meals/entertainment before the 50/100 split is decided — prefer the Meals (50%) / (100%) buckets when known.",
  "Meals & entertainment (rental)": "Meals/entertainment tied to the rental — limited deductibility; the CPA splits.",
  "Entertainment (0%)": "Pure entertainment — NOT deductible under current rules (kept separate so it's excluded from deductions).",
  "Memberships": "Memberships / dues the business PAYS (expense) — distinct from Membership revenue coming in.",
  "Merchant Fees": "Card-processing / payment-processor fees (Stripe, Square) — distinct from bank fees.",
  "Office Expense": "General office operating costs not covered by a more specific line (small software, postage, minor office costs).",
  "Office Supplies": "Physical office supplies (paper, pens, printer).",
  "Phone & Internet": "Business phone and internet service.",
  "Postage": "Postage & shipping.",
  "Rent Expense": "Rent for business space. Use the specific landlord / location sub-accounts where present.",
  "Rent Expense:CubeSmart storage": "Storage-unit rent (CubeSmart).",
  "Rent Expense:Kobalt Investment": "Rent to the Kobalt Investment landlord.",
  "Rent Expense:Three77 Park": "Rent for the Three77 Park space.",
  "Rent Expense:US Property Trust": "Rent to US Property Trust.",
  "Repairs & Maintenance": "Fixing / maintaining equipment or the space. Big improvements are capitalized, not expensed here.",
  "Software": "One-off or recurring software / SaaS used for the business.",
  "Software & Subscriptions": "Software / SaaS and recurring subscriptions for the business.",
  "Taxes and Licenses": "Business taxes, licenses, registration fees (not federal income tax).",
  "Taxes Paid": "Business taxes paid (not federal income tax).",
  "Texas franchise tax (margin tax)": "Texas franchise / margin tax — a deductible business tax.",
  "Travel": "Business travel (airfare, lodging, transport). Meals while traveling go to Meals.",
  "Utilities": "Electricity, gas, water for the business space (phone/internet has its own line).",
  "Utilities Expense": "Electricity, gas, water for the space.",
  "NP Alejandro Siqueira": "A named contractor / professional payee — treat like Contract Labor (confirm the 1099).",
  "2023 F-150 Lightning": "The F-150 vehicle itself — a capitalized asset (depreciated); the CPA handles depreciation.",
  "Ford Focus": "The Ford Focus vehicle — a capitalized asset; the CPA handles depreciation.",
  "Ford Motor Credit - F150": "F-150 loan payments — split into the Interest (expense) and Principal (liability) sub-accounts.",
  "Ford Motor Credit - F150:Interest": "The interest portion of the F-150 loan — the deductible part.",
  "Membership Income": "Gym membership revenue coming in — income.",
  "Membership revenue": "Gym membership revenue coming in — income.",
  "Intercompany — 136 Anita": "The 136 Anita lease GBSL PAYS to Austin ACAA — a GBSL rent expense (mirror of ACAA's income).",
  "Intercompany — 136 Anita (income)": "The 136 Anita lease Austin ACAA RECEIVES from GBSL — rental income to this entity.",

  // — Rental chart (acaa-austin / pflugerville — Sch E) —
  "Advertising & listing": "Listing fees + advertising to fill the rental — Sch E.",
  "Cleaning & maintenance": "Cleaning + upkeep between tenants / stays — Sch E.",
  "Depreciation (CPA)": "Placeholder for depreciation the CPA computes (building / improvements) — not a cash transaction you enter.",
  "HOA / property management": "HOA dues + property-management fees for the rental.",
  "Insurance — rental property": "Landlord / property insurance for the rental — Sch E.",
  "Interest expense (credit card)": "Credit-card interest on the rental's card — deductible against rental income.",
  "Landscaping & pest control": "Yard, landscaping, pest control for the rental.",
  "Mortgage interest": "The interest portion of the rental mortgage — deductible (Sch E). Principal is a liability.",
  "Mortgage payment": "The whole mortgage payment as one line (the P&I split is done in QBO / by the CPA). Counted here for spend tracking.",
  "Professional services (legal, CPA)": "Legal / accounting / professional fees for the rental.",
  "Property taxes": "Property tax on the rental — Sch E.",
  "Repairs & maintenance": "Fixing / maintaining the rental (improvements are capitalized, not expensed here).",
  "Supplies": "General supplies for the property / business.",
  "Supplies & cleaning": "Cleaning + general supplies for the rental.",
  "Travel to property": "Travel to visit / manage the rental — deductible against rental income.",
  "Utilities — rental": "Electricity, gas, water, trash for the rental — Sch E.",
  "Rent income": "Rental income received from tenants — income (Sch E).",
  "HELOC payment": "HELOC payment — counted as spend here; the interest portion is the deductible part (the CPA splits).",

  // — Personal (Sch A / above-the-line / tax) —
  "Mortgage interest — primary home": "Interest on your primary-home mortgage — Sch A itemized deduction. Principal isn't deductible.",
  "State & local taxes (SALT)": "State & local income / property taxes — Sch A itemized (capped at $10k).",
  "Medical & dental": "Out-of-pocket medical / dental — Sch A, only the portion above the AGI floor.",
  "Charitable contributions": "Donations to qualified charities — Sch A itemized (keep receipts).",
  "Charitable contributions (Sch A)": "Donations to qualified charities — Sch A itemized deduction.",
  "HSA contributions": "Health Savings Account contributions — an above-the-line deduction (within IRS limits).",
  "Retirement contributions (IRA/SEP/Solo-401k)": "Retirement-plan contributions — deductible within IRS limits; the CPA confirms the type/limit.",
  "Dependent care (Form 2441)": "Childcare / dependent-care that may qualify for the Form 2441 credit.",
  "529 contributions": "529 college-savings contributions — not federally deductible; may carry a state benefit.",
  "Estimated tax payments — federal": "Quarterly 1040-ES federal estimates — a tax payment, not deductible.",
  "Estimated tax payments — state": "Quarterly state estimated tax payments.",
  "Income tax — federal (prior year)": "A prior-year federal balance-due / settlement payment — non-deductible; kept apart from current-year estimates.",
  "Investment fees & tax prep": "Investment-advisory + tax-prep fees (deductibility is limited under current law).",
  "Home office": "Home-office portion of home costs — needs the Form 8829 calc; the CPA sizes it.",
  "Home maintenance & improvements": "Upkeep / improvements to your home — personal (not deductible; improvements adjust basis).",
  "Education — personal": "Personal education / tuition — generally not a business deduction.",
  "Casualty & theft loss": "Casualty / theft losses — deductible only in a federally-declared disaster (Sch A).",
  "EV / energy-efficiency credits": "Purchases that may qualify for EV / energy-efficiency tax credits (Form 5695 / 8936).",
  "Insurance — personal": "Personal insurance (auto / home / life) — generally not deductible.",
  "Utilities — primary residence": "Home utilities — personal; not deductible unless a home-office portion applies.",
  "Gifts (non-charitable)": "Personal gifts to people — not deductible (donations to charity go under Charitable).",

  // — Personal income —
  "Salary & wages": "W-2 salary / wages coming in — income.",
  "Interest income": "Interest earned — income.",
  "Investment proceeds": "Proceeds from selling investments — income (the CPA handles gains / basis).",
  "Other income": "Miscellaneous income not covered by another line.",
};
